name: main

on: [push]

jobs:
  os-python-matrix:
    strategy:
      matrix:
        os:
          - name: macos
            icon: 🍏
          - name: ubuntu
            icon: 🐧
          - name: windows
            icon: 🪟
        python-version:
          - "3.9"
          - "3.10"
          - "3.12"
          - "3.13"
        exclude:
          - os:
              name: macos
            python-version: "3.13"

    runs-on: ${{ matrix.os.name }}-latest
    name: ${{ matrix.os.icon }} Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: Gr1N/setup-poetry@v9

    - name: Check dependencies
      run: make doctor

    - uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: make install

    - name: Check code
      run: make check

    - name: Test code
      run: make test

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
